const categories = {
  "Fresh Produce": [
    "Vegetables (Tomatoes, Onions, Cabbage)",
    "Fruits (Mangoes, Bananas, Oranges)",
    "Root Crops (Potatoes, Cassava, Yams)",
    "Leafy Greens (Spinach, Kale, Lettuce)",
    "Herbs (Coriander, Basil, Mint)",
    "Exotic Vegetables (Broccoli, Zucchini)",
    "Local Seasonal Produce",
    "Organic Certified Produce",
    "Pre-Washed/Packed Vegetables",
    "Farm-Fresh Eggs",
  ],
  "Grains & Cereals": [
    "Maize/Corn",
    "Wheat",
    "Rice (Paddy/Processed)",
    "Beans (Kidney, Black, Green Grams)",
    "Sorghum",
    "Millet",
    "Barley",
    "Oats",
    "Soybeans",
    "Peas & Lentils",
  ],
  "Livestock & Poultry": [
    "Live Cattle (Dairy/Beef)",
    "Goats & Sheep",
    "Pigs",
    "Live Chickens (Broilers/Layers)",
    "Ducks & Turkeys",
    "Rabbits",
    "Fish (Tilapia, Catfish)",
    "Honey & Bee Products",
    "Day-Old Chicks",
    "Fertile Eggs for Hatching",
  ],
  "Dairy Products": [
    "Fresh Milk",
    "Fermented Milk (Mala, Yoghurt)",
    "Cheese (Cottage, Gouda)",
    "Butter & Ghee",
    "Cream",
    "Ice Cream Mix",
    "Powdered Milk",
    "Flavored Dairy Drinks",
    "Whey Products",
    "Farm-Made Cheese",
  ],
  "Processed Farm Products": [
    "Maize Flour",
    "Wheat Flour",
    "Rice (Polished/Sorted)",
    "Peanut Butter",
    "Sunflower Oil",
    "Fruit Jams & Preserves",
    "Dried Fruits & Nuts",
    "Fermented Products (Kimchi, Sauerkraut)",
    "Smoked Fish/Meat",
    "Packaged Herbs & Spices",
  ],
  "Cash Crops & Export Produce": [
    "Coffee (Arabica/Robusta)",
    "Tea (Green/Black)",
    "Cotton",
    "Tobacco",
    "Sugarcane",
    "Pyrethrum",
    "Avocados (Hass, Fuerte)",
    "Macadamia Nuts",
    "Cashew Nuts",
    "Fresh Cut Flowers",
  ],
  "Seeds & Seedlings": [
    "Certified Maize Seeds",
    "Vegetable Seedlings",
    "Fruit Tree Grafts",
    "Heritage/Indigenous Seeds",
    "Hybrid Seeds",
    "Open-Pollinated Seeds",
    "Pasture Grass Seeds",
    "Ornamental Plant Seedlings",
    "Seed Potatoes",
    "Banana Suckers",
  ],
  "Value-Added Products": [
    "Fruit Juices & Smoothies",
    "Vinegar (Natural Fermented)",
    "Herbal Teas",
    "Farm-Baked Goods",
    "Edible Oils (Cold-Pressed)",
    "Snacks (Roasted Nuts, Banana Chips)",
    "Handmade Soaps (Goat Milk, Aloe)",
    "Beeswax Products (Candles, Balms)",
    "Natural Dyes & Fibers",
    "Farmhouse Wines",
  ],
  "Organic & Specialty Products": [
    "Certified Organic Vegetables",
    "Biodynamic Farm Products",
    "Gluten-Free Grains",
    "Ancient Grains (Quinoa, Amaranth)",
    "Medicinal Herbs",
    "Free-Range Poultry",
    "Grass-Fed Beef",
    "Raw Honey",
    "Farmstead Cheese",
    "Wild-Harvested Products",
  ],
  "Live Plants & Nursery": [
    "Ornamental Plants",
    "Flowering Plants",
    "Fruit Trees (Grafted)",
    "Herb Plants",
    "Suckers (Banana, Pineapple)",
    "Seedlings (Tomato, Cabbage)",
    "Indoor Plants",
    "Landscaping Shrubs",
    "Bonsai Trees",
    "Cactus & Succulents",
  ],
};

export default categories;
