const categories = {
  Electronics: [
    "Smartphones",
    "Laptops",
    "Tablets",
    "Cameras",
    "Televisions",
    "Headphones",
    "Smart Watches",
    "Gaming Consoles",
    "Computer Components",
    "Audio Equipment",
    "Drones",
    "Printers & Scanners",
  ],
  "Clothing & Apparel": [
    "Men's Clothing",
    "Women's Clothing",
    "Kids' Clothing",
    "Baby Clothing",
    "Activewear",
    "Swimwear",
    "Formal Wear",
    "Winter Wear",
    "Lingerie & Sleepwear",
    "Traditional & Cultural",
    "Accessories",
  ],
  "Home & Garden": [
    "Furniture",
    "Home Decor",
    "Kitchen & Dining",
    "Bedding & Bath",
    "Lighting",
    "Storage & Organization",
    "Garden & Outdoor",
    "Tools & Home Improvement",
    "Appliances",
    "Cleaning Supplies",
    "Pet Supplies",
  ],
  Groceries: [
    "Fresh Produce",
    "Dairy & Eggs",
    "Bakery",
    "Meat & Seafood",
    "Frozen Foods",
    "Pantry Staples",
    "Beverages",
    "Snacks",
    "Organic & Natural",
    "International Foods",
    "Baby Food",
    "Alcohol",
  ],
  "Health & Beauty": [
    "Skincare",
    "Hair Care",
    "Makeup",
    "Fragrances",
    "Personal Care",
    "Men's Grooming",
    "Vitamins & Supplements",
    "Medical Supplies",
    "Sexual Wellness",
    "Natural & Organic",
  ],
  "Sports & Outdoors": [
    "Exercise Equipment",
    "Team Sports",
    "Outdoor Recreation",
    "Fitness Accessories",
    "Cycling",
    "Water Sports",
    "Camping & Hiking",
    "Yoga & Pilates",
    "Winter Sports",
    "Fishing",
  ],
  "Toys & Games": [
    "Action Figures",
    "Dolls & Accessories",
    "Building Toys",
    "Board Games",
    "Puzzles",
    "Educational Toys",
    "Outdoor Toys",
    "Baby Toys",
    "Video Games",
    "Collectibles",
  ],
  "Books & Media": [
    "Fiction",
    "Non-Fiction",
    "Children's Books",
    "Textbooks",
    "Audiobooks",
    "E-books",
    "Magazines",
    "Movies & TV Shows",
    "Music",
    "Stationery",
  ],
  Automotive: [
    "Car Parts",
    "Car Accessories",
    "Motorcycle Parts",
    "Tools & Equipment",
    "Car Care",
    "Interior Accessories",
    "Exterior Accessories",
    "Performance Parts",
    "Tires & Wheels",
    "Oils & Fluids",
  ],
  "Office Supplies": [
    "Paper Products",
    "Writing Instruments",
    "Filing & Storage",
    "Office Furniture",
    "Presentation Supplies",
    "Shipping Supplies",
    "Calendars & Planners",
    "Office Electronics",
    "Breakroom Supplies",
  ],
  "Jewelry & Watches": [
    "Necklaces",
    "Bracelets",
    "Earrings",
    "Rings",
    "Watches",
    "Men's Jewelry",
    "Luxury Jewelry",
    "Body Jewelry",
    "Vintage & Antique",
    "Wedding & Engagement",
  ],
  "Baby & Kids": [
    "Nursery Furniture",
    "Baby Gear",
    "Diapering",
    "Feeding",
    "Baby Safety",
    "Baby Care",
    "Kids' Furniture",
    "School Supplies",
    "Party Supplies",
  ],
  "Industrial & Scientific": [
    "Lab Supplies",
    "Industrial Hardware",
    "Safety Equipment",
    "Electrical",
    "Power Tools",
    "Material Handling",
    "HVAC",
    "Hydraulics",
    "Measuring Tools",
  ],
  "Arts & Crafts": [
    "Painting",
    "Drawing",
    "Sewing",
    "Scrapbooking",
    "Jewelry Making",
    "Knitting & Crochet",
    "Party Decorations",
    "Craft Supplies",
    "Fabric",
  ],
  "Travel & Luggage": [
    "Luggage",
    "Travel Accessories",
    "Backpacks",
    "Travel Bags",
    "Travel Organizers",
    "Travel Comfort",
    "Passport Covers",
    "Luggage Tags",
    "Travel Adapters",
  ],
};

export default categories;
