export const industries = [
  "Advertising & Marketing",
  "Aerospace & Defense",
  "Agriculture & Farming",
  "Automotive",
  "Banking & Financial Services",
  "Biotechnology",
  "Construction & Real Estate",
  "Consulting",
  "Consumer Goods",
  "Education",
  "Energy & Utilities",
  "Entertainment & Media",
  "Fashion & Apparel",
  "Food & Beverage",
  "Gaming",
  "Government & Public Sector",
  "Healthcare & Medical",
  "Hospitality & Tourism",
  "Insurance",
  "Legal Services",
  "Logistics & Transportation",
  "Manufacturing",
  "Mining & Metals",
  "Non-Profit & NGO",
  "Pharmaceutical",
  "Retail & E-commerce",
  "Software & IT Services",
  "Sports",
  "Telecommunications",
  "Technology",
  "Other",
];
